apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: airflow
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: airflow-init
    spec:
      containers:
        - name: init
          image: airflowacrcluster.azurecr.io/airflow:latest
          envFrom:
            - secretRef:
                name: airflow-secrets
          command:
            - bash
            - -c
            - >
              set -ex;
              airflow db init;
              airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs
      restartPolicy: Never
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          emptyDir: {} # or use another PVC if logs need persistence
