apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:MyStrongPassword123@airflowpgserver26718.postgres.database.azure.com/postgres"
  AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
  ENTSOE_API_KEY: "808aeda6-8be2-421e-bfca-2165074d69a1"
