apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  type: LoadBalancer
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
