apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflowadmin@postgres-server-airflow:airflowadmin@postgres-server-airflow.postgres.database.azure.com:5432/flexibleserverdb?sslmode=require
  AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
  ENTSOE_API_KEY: "808aeda6-8be2-421e-bfca-2165074d69a1"
