apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: airflowacrcluster.azurecr.io/airflow:latest
          command: ["airflow", "scheduler"]
          envFrom:
            - secretRef:
                name: airflow-secrets
          env:
            - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
            - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
