apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: airflow
spec:
  template:
    spec:
      containers:
        - name: init
          image: airflowacr26970.azurecr.io/airflow:latest
          envFrom:
            - secretRef:
                name: airflow-secrets
          command:
            - bash
            - -c
            - >
              set -ex;
              airflow db init;
              airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com
      restartPolicy: Never
