apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: airflowacr26970.azurecr.io/airflow:latest
          command: ["webserver"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
            - name: plugins-volume
              mountPath: /opt/airflow/plugins
            - name: secrets-store-inline
              mountPath: /etc/secrets-store
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: plugins-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: secrets-store-inline # This defines the volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "airflow-secrets"
