apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: airflowacr26970.azurecr.io/airflow:latest
          command: ["scheduler"]
          envFrom:
            - secretRef:
                name: airflow-secrets
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
            - name: plugins-volume
              mountPath: /opt/airflow/plugins
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: plugins-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
