apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: airflowacrcluster.azurecr.io/airflow:latest
          command: ["webserver"]
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: airflow-secrets
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
            - name: plugins-volume
              mountPath: /opt/airflow/plugins
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: plugins-volume
          emptyDir: {}
