apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: airflow
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: airflowfileshare
    volumeAttributes:
      shareName: airflowfileshare
      storageAccount: myairflowstorage
    nodeStageSecretRef:
      name: azure-secret
      namespace: airflow
