apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: airflow-dags-pv
  resources:
    requests:
      storage: 5Gi
