apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
  volumeAttributes:
    secretName: azure-file-secret
