apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflowadmin:etladmin@airflow-pgsql.postgres.database.azure.com:5432/postgres
  AIRFLOW__CORE__FERNET_KEY: nZPrEH1-yYAfsRuetKESCXmmDZdqNKFu4Y3zhnNvjqg=
  ENTSOE_API_KEY: 808aeda6-8be2-421e-bfca-2165074d69a1
