# values.yaml
airflow:
  config:
    # Airflow core settings
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:MyStrongPassword123@$PG_NAME.postgres.database.azure.com/airflow"
    AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    # Webserver settings
    AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
    AIRFLOW__WEBSERVER__RBAC: "true"

    # API settings
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"

# Only keep non-Airflow-specific env vars here
env:
  - name: ENTSOE_API_KEY
    value: "808aeda6-8be2-421e-bfca-2165074d69a1"
