name: Deploy Airflow DAGs to Azure File Share

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"

env:
  ACR_NAME: airflowacrcluster
  AKS_RESOURCE_GROUP: airflow-rg
  AKS_CLUSTER_NAME: airflow-aks
  IMAGE_NAME: airflow
  IMAGE_TAG: latest
  FILE_SHARE_NAME: pvc-a97254bb-1499-4e7e-bc74-cd016e8fa2bf
  DAGS_DIR_NAME: dags

jobs:
  deploy:
    name: Upload DAGs to Azure File Share
    runs-on: ubuntu-latest
    environment: etl-workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Share and DAGs Directory Exists
        run: |
          echo "📂 Checking/creating file share and DAGs directory..."

          az storage share-rm create \
            --resource-group $AKS_RESOURCE_GROUP \
            --storage-account ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --name $FILE_SHARE_NAME || true

          az storage directory create \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --share-name $FILE_SHARE_NAME \
            --name $DAGS_DIR_NAME || true

      - name: Upload DAGs using Azure CLI
        run: |
          echo "📤 Uploading DAGs using az storage file upload-batch..."

          az storage file upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --destination "$FILE_SHARE_NAME/$DAGS_DIR_NAME" \
            --source "./dags" \
            --connection-string ${{ secrets.STORAGE_CONNECTION_STRING }}

      - name: Restart Airflow Deployments
        run: |
          echo "🔄 Restarting Airflow pods to reload DAGs..."
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
          kubectl rollout restart deployment airflow-webserver -n airflow
          kubectl rollout restart deployment airflow-scheduler -n airflow
          echo "✅ Restart complete!"
