name: Deploy Airflow DAGs to Azure File Share

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"

env:
  ACR_NAME: airflowacrcluster
  AKS_RESOURCE_GROUP: airflow-rg
  AKS_CLUSTER_NAME: airflow-aks
  IMAGE_NAME: airflow
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Upload DAGs to Azure File Share
    runs-on: ubuntu-latest
    environment: etl-workflow

    steps:
      - name: Test DNS resolution
        run: |
          nslookup ${{ secrets.AZURE_STORAGE_ACCOUNT }}.file.core.windows.net

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Mount Azure File Share
        run: |
          for i in {1..5}; do
            if sudo mount -t cifs //${{ secrets.AZURE_STORAGE_ACCOUNT }}.file.core.windows.net/${{ secrets.AZURE_FILE_SHARE }} dags-mount -o vers=3.0,username=${{ secrets.AZURE_STORAGE_ACCOUNT }},password=${{ secrets.AZURE_STORAGE_KEY }},dir_mode=0777,file_mode=0777,serverino; then
              echo "DAGs uploaded to Azure File Share"
              break
            else
              echo "Attempt $i failed. Retrying in 5 seconds..."
              sleep 5
            fi
          done

      - name: Debug mount command
        run: |
          echo "Mounting: //${{ secrets.AZURE_STORAGE_ACCOUNT }}.file.core.windows.net/${{ secrets.AZURE_FILE_SHARE }}"

      - name: Unmount File Share
        run: |
          sudo umount dags-mount

      - name: Restart Airflow Deployments
        run: |
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
          kubectl rollout restart deployment airflow-webserver -n airflow
          kubectl rollout restart deployment airflow-scheduler -n airflow
