name: Deploy Airflow DAGs to Azure File Share

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"

env:
  ACR_NAME: airflowacrcluster
  AKS_RESOURCE_GROUP: airflow-rg
  AKS_CLUSTER_NAME: airflow-aks
  IMAGE_NAME: airflow
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Upload DAGs to Azure File Share
    runs-on: ubuntu-latest
    environment: etl-workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install and Use AzCopy for DAG Upload
        run: |
          echo "📥 Installing AzCopy..."
          wget -q -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
          tar -xf azcopy.tar.gz --strip-components=1
          sudo mv azcopy /usr/local/bin/

          echo "🚀 Uploading DAGs using AzCopy..."
          azcopy copy "./dags" \
            "https://f314a19b0d8b1437a879f40.file.core.windows.net/pvc-a97254bb-1499-4e7e-bc74-cd016e8fa2bf/dags?${{ secrets.AZURE_STORAGE_KEY }}" \
            --recursive \
            --log-level INFO

          echo "✅ Upload complete. Verifying..."
          azcopy list "https://f314a19b0d8b1437a879f40.file.core.windows.net/pvc-a97254bb-1499-4e7e-bc74-cd016e8fa2bf/dags?${{ secrets.AZURE_STORAGE_KEY }}"

      - name: Restart Airflow Deployments
        run: |
          echo "🔄 Restarting Airflow pods to reload DAGs..."
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
          kubectl rollout restart deployment airflow-webserver -n airflow
          kubectl rollout restart deployment airflow-scheduler -n airflow
          echo "✅ Restart complete!"
